name: Waka Readme

on:
  workflow_run:
    workflows: [ "README build" ]
    types:
      - completed
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "Updated dev metrics"
          COMMIT_USERNAME: "penjc"
          COMMIT_EMAIL: "jcpeng3-c@my.cityu.edu.hk"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}